name: Run Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_GROQ_API_KEY: ${{ secrets.GROQAPIKEY }}
          file_name: .env
          fail_on_empty: true

      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
              
      - run: npm i && npx playwright install
      - run: npx codeceptjs def && npm test
      - run: npx codeceptjs def && xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npm test

